apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    pod-security.kubernetes.io/enforce: restricted
  name: kalm-benchmark
---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
  name: kalm-benchmark
spec:
  hard:
    cpu: 30
    memory: 20Gi
    pods: 1000
---
apiVersion: v1
kind: LimitRange
metadata:
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
  name: kalm-benchmark
spec:
  limits:
    - default:
        cpu: 100m
        memory: 1Mi
      defaultRequest:
        cpu: 1m
        memory: 1Ki
      max:
        cpu: 100m
        memory: 10Mi
      min:
        cpu: 1m
        memory: 1Ki
      type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
  name: kalm-benchmark
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
