apiVersion: v1
kind: Namespace
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
    pod-security.kubernetes.io/enforce: restricted
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
spec:
  hard:
    cpu: 30
    memory: 20Gi
    pods: 1000
---
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
spec:
  limits:
    - default:
        cpu: 100m
        memory: 1Mi
      defaultRequest:
        cpu: 1m
        memory: 1Ki
      max:
        cpu: 100m
        memory: 10Mi
      min:
        cpu: 1m
        memory: 1Ki
      type: Container
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy-filler-dedicated-sa
  namespace: np-001-namespace-without-network-policy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kalm-benchmark
      check: NP-001
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/app: runtime/default
        container.seccomp.security.alpha.kubernetes.io/app: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app.kubernetes.io/part-of: kalm-benchmark
        check: NP-001
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              weight: 1
      automountServiceAccountToken: false
      containers:
        - image: nginx@sha256:aed492c4dc93d2d1f6fe9a49f00bc7e1863d950334a93facd8ca1317292bf6aa
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
          name: app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          resources:
            limits:
              cpu: 1m
              ephemeral-storage: 1Mi
              memory: 1Mi
            requests:
              cpu: 1m
              ephemeral-storage: 1Mi
              memory: 1Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 31337
            runAsNonRoot: true
            runAsUser: 31337
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      hostIPC: false
      hostNetwork: false
      hostPID: false
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: default-priority
      securityContext:
        runAsGroup: 31337
        runAsNonRoot: true
        runAsUser: 31337
        seLinuxOptions:
          level: s0:c123,c456
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: np-001-namespace-without-network-policy-filler-dedicated-sa
