apiVersion: v1
kind: Namespace
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace|.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace|.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
spec:
  hard:
    cpu: 30
    memory: 20Gi
    pods: 1000
---
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    check_path: NetworkPolicy.metadata.namespace|.metadata.namespace
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: NP-001
  name: np-001-namespace-without-network-policy
  namespace: np-001-namespace-without-network-policy
spec:
  limits:
    - default:
        cpu: 100m
        memory: 1Mi
      defaultRequest:
        cpu: 1m
        memory: 1Ki
      max:
        cpu: 100m
        memory: 10Mi
      min:
        cpu: 1m
        memory: 1Ki
      type: Container
