apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: POD-043-1
  name: pod-043-1-mount-azure-cloud-credentials-dedicated-sa
  namespace: kalm-benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    check_path: .spec.volumes[]|.spec.volumes[].hostPath|.spec.volumes[].hostPath.path|.spec.containers[].volumeMounts[]
    description: Mounting Docker socket (Unix socket) enables container to access Docker internals, retrieve sensitive information and execute Docker commands.
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: POD-043-1
  name: pod-043-1-mount-azure-cloud-credentials
  namespace: kalm-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kalm-benchmark
      check: POD-043-1
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/app: runtime/default
        container.seccomp.security.alpha.kubernetes.io/app: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app.kubernetes.io/part-of: kalm-benchmark
        check: POD-043-1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              weight: 1
      automountServiceAccountToken: false
      containers:
        - image: nginx@sha256:aed492c4dc93d2d1f6fe9a49f00bc7e1863d950334a93facd8ca1317292bf6aa
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
          name: app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          resources:
            limits:
              cpu: 1m
              ephemeral-storage: 1Mi
              memory: 1Mi
            requests:
              cpu: 1m
              ephemeral-storage: 1Mi
              memory: 1Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 31337
            runAsNonRoot: true
            runAsUser: 31337
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /etc/kubernetes/azure.json
              name: mnt-azure
              readOnly: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: default-priority
      securityContext:
        runAsGroup: 31337
        runAsNonRoot: true
        runAsUser: 31337
        seLinuxOptions:
          level: s0:c123,c456
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: pod-043-1-mount-azure-cloud-credentials-dedicated-sa
      volumes:
        - hostPath:
            path: /etc/kubernetes/azure.json
            type: File
          name: mnt-azure
