apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    check_path: .spec.allowedHostPaths
    description: Attackers can use a writable hostPath to gain persistence on underlying host system
    expected: pass
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: PSP-006-3
  name: psp-006-3-disallow-all-host-paths-properly
  namespace: kalm-benchmark
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - pathPrefix: /does/not/exist
      readOnly: true
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: MustRunAs
    seLinuxOptions:
      level: s0:c123,c456
  supplementalGroups:
    rule: RunAsAny
