apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    check_path: .spec.readOnlyRootFilesystem
    description: having a writeable root filesystem allows attackers to compromising the machine through permanent local changes
    expected: alert
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: PSP-011-2
  name: psp-011-2-allowing-read-only-root-filesystem
  namespace: kalm-benchmark
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - pathPrefix: /foo/none/allowed
      readOnly: true
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: MustRunAs
    seLinuxOptions:
      level: s0:c123,c456
  supplementalGroups:
    rule: RunAsAny
