apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    check_path: .spec.runAsUser
    description: a user should not have elevated privileges
    expected: alert
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: PSP-007-2
  name: psp-007-2-allow-root-users-in-pods-uid-range
  namespace: kalm-benchmark
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - pathPrefix: /foo/none/allowed
      readOnly: true
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
    - ALL
  runAsUser:
    ranges:
      - max: 65535
        min: 0
    rule: MustRunAs
  seLinux:
    rule: MustRunAs
    seLinuxOptions:
      level: s0:c123,c456
  supplementalGroups:
    rule: RunAsAny
