apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    check_path: .metadata.annotations.apparmor.security.beta.kubernetes.io/allowedProfileNames|.metadata.annotations[apparmor.security.beta.kubernetes.io/allowedProfileNames]
    description: Not hardening a linux system can increase the impact of a compromise
    expected: alert
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: PSP-013-3
  name: psp-013-3-not-restricting-allowed-apparmor-profiles
  namespace: kalm-benchmark
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
    - pathPrefix: /foo/none/allowed
      readOnly: true
  fsGroup:
    rule: RunAsAny
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: MustRunAs
    seLinuxOptions:
      level: s0:c123,c456
  supplementalGroups:
    rule: RunAsAny
