apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    check_path: ClusterRole.rules[].verbs|Role.rules[].verbs|.rules[].verbs
    description: Attackers can use destructive permissions to destroy data and resources
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-013-3
  name: rbac-013-3-cluster-role-destroy-resources
  namespace: kalm-benchmark
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - services
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
      - jobs
      - cronjobs
    verbs:
      - delete
