apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    check_path: ClusterRole.rules[].resources|Role.rules[].resources|.rules[].resources
    description: Attackers who have permissions to retrieve the secrets can access sensitive information
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-002-3
  name: rbac-002-3-secret-read-watch
  namespace: kalm-benchmark
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - watch
