apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    check_path: ClusterRole.rules[].verbs|Role.rules[].verbs|.rules[].verbs
    description: Allowing wildcards violates principle of least privilege
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-003-6
  name: rbac-003-6-cluster-all-ns-verbs
  namespace: kalm-benchmark
rules:
  - apiGroups:
      - ""
    resources:
      - jobs
    verbs:
      - get
