apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    check_path: ClusterRole.rules[].resources|ClusterRole.rules[].verbs|Role.rules[].resources|Role.rules[].verbs|.rules[].resources|.rules[].verbs
    description: Attackers can escalate privileges if they can update roles
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-010-1
  name: rbac-010-1-role-destroy-resources
  namespace: kalm-benchmark
rules:
  - apiGroups:
      - ""
    resources:
      - rolebindings
    verbs:
      - bind
