apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    check_path: ClusterRoleBinding.subjects[].name|RoleBinding.subjects[].name|.subjects[].name
    description: the default servicaccount should never be actively used
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-007-2
  name: rbac-007-2-cluster-role-binds-default-serviceaccount-rb-rbac-007-2-cluster-role-bind-default-sa
  namespace: kalm-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-007-2-cluster-role-bind-default-sa
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: default
    namespace: kalm-benchmark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    check_path: ClusterRoleBinding.subjects[].name|RoleBinding.subjects[].name|.subjects[].name
    description: the default servicaccount should never be actively used
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-007-2
  name: rbac-007-2-cluster-role-bind-default-sa
  namespace: kalm-benchmark
rules: []
