apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    check_path: ClusterRoleBinding.subjects[].name|RoleBinding.subjects[].name|.subjects[].name
    description: the default servicaccount should never be actively used
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-007-1
  name: rbac-007-1-role-binds-default-serviceaccount-rb-rbac-007-1-role-bind-default-sa
  namespace: kalm-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-007-1-role-bind-default-sa
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: default
    namespace: kalm-benchmark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    check_path: ClusterRoleBinding.subjects[].name|RoleBinding.subjects[].name|.subjects[].name
    description: the default servicaccount should never be actively used
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-007-1
  name: rbac-007-1-role-bind-default-sa
  namespace: kalm-benchmark
rules: []
