apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    check_path: ClusterRole.rules[].verbs|Role.rules[].verbs|.rules[].verbs
    description: attackers may want to delete events in an attempt to avoid detection of their activity
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-014-1
  name: rbac-014-1--destroy-events
  namespace: kalm-benchmark
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - delete
