apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    check_path: ClusterRoleBinding.subjects[].name|RoleBinding.subjects[].name|.subjects[].name
    description: all service accounts should be bound to roles
    expected: alert
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-016
  name: rbac-016-ronin-sa
  namespace: kalm-benchmark
