apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  annotations:
    check_path: .spec.containers[].image
    description: Specify an explicit tag or digest to have full control over the running container image
    expected: pass
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: SC-002-1
  name: sc-002-1-tag-instead-of-digest-is-fine-dedicated-sa
  namespace: kalm-benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    check_path: .spec.containers[].image
    description: Specify an explicit tag or digest to have full control over the running container image
    expected: pass
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: SC-002-1
  name: sc-002-1-tag-instead-of-digest-is-fine
  namespace: kalm-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kalm-benchmark
      check: SC-002-1
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/app: runtime/default
        container.seccomp.security.alpha.kubernetes.io/app: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app.kubernetes.io/part-of: kalm-benchmark
        check: SC-002-1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
              weight: 1
      automountServiceAccountToken: false
      containers:
        - image: nginx:1.12.6
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
          name: app
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          resources:
            limits:
              cpu: 1m
              ephemeral-storage: 1Mi
              memory: 1Mi
            requests:
              cpu: 1m
              ephemeral-storage: 1Mi
              memory: 1Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 31337
            runAsNonRoot: true
            runAsUser: 31337
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      hostIPC: false
      hostNetwork: false
      hostPID: false
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: default-priority
      securityContext:
        runAsGroup: 31337
        runAsNonRoot: true
        runAsUser: 31337
        seLinuxOptions:
          level: s0:c123,c456
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sc-002-1-tag-instead-of-digest-is-fine-dedicated-sa
