name: Generate Benchmark manifests

on: 
  workflow_dispatch:
  push:
    branches: ["main"]
    #paths:
      # regenerate manifests whenever the IaC was modified
      #- '**/manifest_generator/**/*.py'  

env:
  BIN_NAME: 'kalm-benchmark.whl'
  
jobs:
  build-kalm-benchmark:
    uses: ./.github/workflows/build.yml
  gen-manifests:
    runs-on: ubuntu-latest
    needs: build-kalm-benchmark
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/download-artifact@v3
        name: Download Kalm-Benchmark
        with:
          name: ${{ env.BIN_NAME }}
      - name: Display structure of downloaded files
        run: ls -la
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          #cache: 'npm'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Kalm-Benchmark
        run: pip install ${{ env.BIN_NAME }}
